
<!-- todo: design-->

The experiment followed a
2 (*material*: probabilistic vs. mixed deterministic) $\times$
2 (*instructions*: sequence concealed vs. sequence revealed) $\times$
7 (*block pair*) $\times$
3 (*stimulus-location regularity*: nonregular, regular, deterministic)
design with repeated measures on the last two factors.

## Participants

```{r include = FALSE}
library(papaja)
demographics <- list.files(path = file.path(rprojroot::find_rstudio_root_file(), "studies", "cpl8", "data-raw", "demographics"), full.names = TRUE) |>
  Filter(f = function(x) file.size(x) > 0) |>
  lapply(read.csv, encoding = "latin1") |>
  do.call(what = "rbind") |>
  within({
    gender          <- factor(gender, levels = c("weiblich", "männlich", "divers"), labels = c("female", "male", "diverse"))
    native_language <- factor(native_language, levels = c("Deutsch", "andere"), labels = c("German", "other"))
    impaired_vision <- factor(impaired_vision,  levels = c("nein", "ja"), labels = c("no", "yes"))
  })

gender <- table(demographics$gender)
median_age <- paste0("$\\mathit{Md} = ", median(demographics$age), "~\\mathrm{years}$")
range_age <- paste(range(demographics$age), collapse = " and ")
```

`r apa_num(nrow(demographics), numerals = FALSE, capitalize = TRUE)` participants (`r gender[["female"]]` women) aged between `r range_age` years (`r median_age`) completed the study. Most were undergraduates from University of Cologne. Participants were randomly assigned to experimental conditions. They received either course credit or 7.50 Euro for their participation.



## Materials and Procedure

For each participant anew, we generated a random permutation of the six possible stimulus locations which served as the six-item sequence.
For participants in the *probabilistic sequence* conditions, stimulus locations followed this sequence with a probability of .6; otherwise, another stimulus location was randomly selected from a uniform distribution (excluding immediate repetitions).
For participants in the *mixed-deterministic sequence* conditions, stimulus locations deterministically followed this six-item sequence in deterministic blocks;
in random blocks, stimulus locations were randomly selected from a uniform distribution (excluding immediate repetitions).
The order of random vs. deterministic blocks was randomly selected for these participants:
Either blocks 1, 3, 5, 7, 9, 11, 13, or 2, 4, 6, 8, 10, 12, 14 were deterministic.
Note that in random blocks, approximately 1/5 = 20% of stimuli followed the sequence by chance.
Hence, all participants received stimulus materials that consisted of roughly 60% regular stimulus locations.

Participants in the *sequence concealed* conditions did not receive any a-priori information that stimulus locations follow an underlying sequential structure.
By contrast, participants in the *sequence revealed* conditions were informed that stimulus locations followed such a regularity.
If these participants worked on probabilistic materials, they were informed that on 60% of trials, the stimulus would be presented in regular location, and in 40% of trials, it would be randomly selected.
If these participants worked on mixed-deterministic materials, they were informed about the blocked structure of deterministic vs. random blocks, with exact information about which in blocks stimuli would follow the sequence and in which blocks stimulus locations would be randomly selected.
Moreover, participants in the *sequence revealed* conditions were explicitly encouraged to try to use their advance sequence knowledge to optimize task performance.
They were then informed about the exact six-item structure of their sequence (e.g., "2--1--6--5--3--4") and they performed 18 trials of the sequence (i.e. three repetitions of the full sequence).

All participants worked on 14 blocks (144 trials each) of an SRTT.
On each trial of the experiment, 
the six possible stimulus locations were marked with grey outlines of rectangles on a black screen.
After 250msec, the imperative stimulus was presented in one of the six stimulus locations.
If a response was given before the stimulus had occurred,
participants were reminded to only press a key after the stimulus had occurred for 2sec.
To obtain a significant proportion of error responses, we used a response deadline of 500msec.
To allow participants to get used to the task, in the first block, we used response deadlines of 900, 800, 700, 600msec for 24 trials each before switching to 500msec for the remainder of the experiment.
If the response deadline had been exceeded, a warning sign together with feedback was presented for 1200msec.
If the wrong key had been pressed, "wrong key" was presented for 300msec.

Following the SRTT, we assessed explicit sequence knowledge in a post-experimental interview.
Participants were told that they had been assigned to an experimental condition with or without a sequential structure,
and were asked to indicate if they believed that they were in a sequenced or a random condition.
If they believed that they were in a sequence condition, they were then asked to freely reproduce the sequence.
Finally, all participants were asked to reproduce the sequence in a forced-choice manner.
Participants were then thanked and debriefed.

## Data preparation

Because an SRTT with a response deadline can be a demanding task, we screened participant data for the proportion of too-slow responses and error rates: 
We excluded participants who, in one of block pairs 2-7, exceeded an error rate of 50% or responded too slowly on more than 30% of trials.
We also excluded data of two participants who did not finish the study and of five participants whose response times were not properly saved.

Furthermore, trials that followed an erroneous response or a response that exceeded the response deadline were excluded from analyses.
We also excluded the first four trials of each block, and trials with responses faster than 20ms or slower than 2s.


<!--
- RSI = 250ms
- too fast: feedback for 2sec
- response deadline exceeded: feedback for 1200msec
- error feedback: 300msec
- response deadline 500msec, except for the first 96 trials: 24 * 900msec, 24 * 800msec, 24 * 700msec, 24 * 600msec
-->
